
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POSITIVE1 = 21;
  public static final int COMILLA2 = 17;
  public static final int DOSPUNTOS = 2;
  public static final int COMILLA1 = 16;
  public static final int CADENA = 11;
  public static final int LETRA = 15;
  public static final int GUIONC = 3;
  public static final int KLEENE1 = 20;
  public static final int FLECHA = 7;
  public static final int CONCAT1 = 18;
  public static final int CONJ1 = 10;
  public static final int ID = 12;
  public static final int OPTIONAL1 = 22;
  public static final int CARACTER = 13;
  public static final int SEPARADOR = 8;
  public static final int COMA = 9;
  public static final int OR1 = 19;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int LLAVE2 = 6;
  public static final int LLAVE1 = 5;
  public static final int PUNTOCOMA = 4;
  public static final int ENTERO = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOSPUNTOS",
  "GUIONC",
  "PUNTOCOMA",
  "LLAVE1",
  "LLAVE2",
  "FLECHA",
  "SEPARADOR",
  "COMA",
  "CONJ1",
  "CADENA",
  "ID",
  "CARACTER",
  "ENTERO",
  "LETRA",
  "COMILLA1",
  "COMILLA2",
  "CONCAT1",
  "OR1",
  "KLEENE1",
  "POSITIVE1",
  "OPTIONAL1"
  };
}

